### ISSUE TITLE
Add flag to change copy command

### ISSUE THREAD

**Issue by zQueal** [marcwebbie/passpie#77]
I'm running from Windows. Obviously I don't have access to `xcopy` -- however, I do have CLI utilities for copying and pasting from the CLI. They're `pclip` and `gclip`. Adding a setting for `~/.passpierc` to change the `xsel` or `xcopy` commands to something compatible with Windows would be great.

```
headers:
 - name
 - login
 - password
copy_command: pclip
colors:
 login: green
 name: yellow
 password: cyan 
```
