### ISSUE TITLE
Passpie doesn't find credentials with local config path to remote repository

### ISSUE THREAD

**Issue by chtiprog** [marcwebbie/passpie#86]
Passpie is not finding my credentials when remote repository path set on local config

 
```yaml
# .config
path: git@example.com/chtiprog/passpiedb.git
autopush: origin/master
```
