### ISSUE TITLE
Add aliases configuration

### ISSUE THREAD

**Issue by marcwebbie** [marcwebbie/passpie#92]
Example:

```yaml
# .config
aliases:
  rm: remove
  a: add
  e: update
  st: status
```
