### ISSUE TITLE
Remove short_commands config

### ISSUE THREAD

**Issue by marcwebbie** [marcwebbie/passpie#93]
With aliases as in #92 the need for automatic aliases. Backward incompatible.

To have a similar effect one could set aliases for all commands:

```yaml
aliases:
  a: add
  cm: complete
  cf: config
  cp: copy
  e: export
  im: import
  in: init
  ls: list
  lo: log
  p: purge
  rm: remove
  rs: reset
  se: search
  st: status
  u: update
```
